# Generated by Django 4.0.6 on 2022-07-16 06:32

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_functionality_app'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='app',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='app',
            name='users',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='functionality',
            name='helpers',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='functionality',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.functionality_image_upload_location),
        ),
        migrations.AlterField(
            model_name='functionality',
            name='procudure',
            field=models.JSONField(default=list),
        ),
    ]
