# Generated by Django 4.0.6 on 2022-07-23 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_app_users_appuser_functionality_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='access_token',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='folders',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('path', models.CharField(max_length=256)),
                ('dot_notation', models.CharField(max_length=256)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.app')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
