# Generated by Django 4.0.6 on 2022-07-24 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_app_access_token_app_folders_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='dot_notation',
        ),
    ]
