# Generated by Django 4.0.6 on 2022-07-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_folders_app_ignore_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='folders',
            field=models.JSONField(default=list),
        ),
    ]
