# Generated by Django 4.0.3 on 2022-07-31 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_handler_functionality_front_end_handler'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionality',
            name='back_end_handler',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='functionality',
            name='front_end_handler',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
