# Generated by Django 4.0.3 on 2022-07-31 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_functionality_back_end_handler_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionality',
            name='back_end_gist',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='functionality',
            name='front_end_gist',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
