# Generated by Django 4.0.3 on 2022-08-01 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_functionality_back_end_gist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='folders',
            new_name='fe_folders',
        ),
        migrations.RenameField(
            model_name='app',
            old_name='ignore_files',
            new_name='fe_ignore_files',
        ),
        migrations.RenameField(
            model_name='app',
            old_name='link',
            new_name='fe_link',
        ),
        migrations.RenameField(
            model_name='app',
            old_name='repository',
            new_name='fe_repo',
        ),
        migrations.RenameField(
            model_name='app',
            old_name='access_token',
            new_name='fe_token',
        ),
    ]
