# Generated by Django 4.0.3 on 2022-08-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_folders_app_fe_folders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='be_ignore_files',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='app',
            name='be_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='be_repo',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='be_token',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='folders',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='app',
            name='fe_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='fe_repo',
            field=models.URLField(null=True),
        ),
    ]
