# Generated by Django 4.0.3 on 2022-08-01 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_app_be_ignore_files_app_be_link_app_be_repo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='folders',
            new_name='be_folders',
        ),
    ]
