# Generated by Django 4.0.3 on 2022-08-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_folders_app_be_folders'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='end',
            field=models.CharField(choices=[('FRONT', 'FRONT'), ('BACK', 'BACK')], default='FRONT', max_length=8),
        ),
    ]
