# Generated by Django 4.0.3 on 2022-08-15 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_functionality_back_end_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionality',
            name='dev_manual',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='functionality',
            name='dev_video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='functionality',
            name='user_manual',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='functionality',
            name='user_video',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
