# Generated by Django 4.0.3 on 2022-08-15 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_functionality_dev_manual_functionality_dev_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionality',
            name='user_video',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
