# Generated by Django 4.0.6 on 2022-12-10 14:34

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0018_alter_functionality_user_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='functionality',
            name='helpers',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='functionality',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.functionality_image_upload_location),
        ),
        migrations.AlterField(
            model_name='functionality',
            name='procudure',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='functionality',
            name='user_manual',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
