# Generated by Django 4.0.3 on 2022-12-11 02:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0019_app_user_alter_functionality_helpers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='collaborators',
            field=models.ManyToManyField(related_name='apps', to=settings.AUTH_USER_MODEL),
        ),
    ]
