# Generated by Django 4.0.6 on 2023-07-20 03:15

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_app_be_folders_alter_app_be_ignore_files_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionality',
            name='description',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='functionalitycategory',
            name='Functionalities',
            field=models.ManyToManyField(related_name='categories', to='core.functionality'),
        ),
    ]
