# Generated by Django 4.0.6 on 2023-07-23 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_functionality_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionality',
            name='description',
            field=models.CharField(max_length=512),
        ),
    ]
