# Generated by Django 4.0.6 on 2023-07-23 03:40

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_functionality_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionality',
            name='description',
            field=django_quill.fields.QuillField(),
        ),
    ]
